apiVersion: v1
kind: Service
metadata:
  name: website-service
  labels:
    name: website-service
    app: website-app
spec:
  selector:
    name: website-pod
    app: website-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31455
